FROM {{ namespace }}/{{ image_prefix }}neutron-server:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

USER root

{% block neutron_server_cisco_vts_ml2_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% set neutron_server_cisco_vts_ml2_packages = [
        'python-cisco-controller'
    ] %}
    
COPY repofiles/cisco-vts.repo /etc/yum.repos.d/cisco-vts.repo

{{ macros.install_packages(neutron_server_cisco_vts_ml2_packages | customizable("packages")) }}

{% elif install_type == 'source' %}

ADD plugins-archive /

{% set neutron_server_cisco_vts_ml2_plugins_pip_packages = [
    '/plugins/*'
] %}

RUN if [ "$(ls /plugins)" ]; then \
        {{ macros.install_pip(neutron_server_cisco_vts_ml2_plugins_pip_packages | customizable("pip_packages")) }}; \
    fi

{% endif %}

{% block neutron_server_cisco_vts_ml2_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER neutron
